[package]
name = "rhusics"
version = "0.1.0"
authors = ["Simon Rönnberg <simon.ronnberg@codemill.se>"]

[features]
double = []

[dependencies]
cgmath = "0.15"
collision = { path = "../collision-rs" }
specs = { git = "https://github.com/slide-rs/specs/"}
"specs-derive" = { git = "https://github.com/slide-rs/specs/"}
log = "*"

[dev-dependencies]
assert_approx_eq = "*"
